### ISSUE TITLE
Add ability to set publisher information

### ISSUE THREAD

**Issue by TingPing** [flathub/linux-store-frontend#146] opened 2018-10-30 12:32 UTC
Some applications, such as GIMP, are official packages and just have a generic "Flathub maintainers" publisher which is misleading for users. We need some system for admins to manually toggle an application as official and present that in some form.

**Comment by jurf** [comment] 2019-01-04 13:22
Duplicate of #48?

**Closed** 2019-01-04 14:20 UTC
