### ISSUE TITLE
Filter by architecture

### ISSUE THREAD

**Issue by zoglesby** [flathub/linux-store-frontend#100] opened 2018-05-07 23:02 UTC
It would be nice to be able to filter the view of flathub on the web based on what is available for a specific architecture. For example a check box to show only apps available for x86_64 or aarch64.

**Comment by jgarciao** [comment] 2018-05-08 05:45
Duplicate of https://github.com/flathub/linux-store-frontend/issues/39

**Closed by jgarciao** 2018-05-08 05:45 UTC
