### ISSUE TITLE
[Feature request] Make plugins visible & navigatable

### ISSUE THREAD

**Issue by Nokia808** [flathub/linux-store-frontend#232] opened 2020-06-25 05:04 UTC
Hi. 
Currently, plug-ins not shown at all ! This is a shortage. 
To improve the site, there should be a way to make them visible. Also, users should be able to navigate across them after seeing them, so that she/he can view the data dictated for them exactly as for applications. 

Plug-ins should, also, appearing in search result of the site. I suggest to add a filter to search so that user can search generally (applications + plug-ins), or search for applications only, or search only for plug-ins

I suggest on you to make a list for plug-ins available within page of application, as in GNOME software. Let we take GIMP as example:
see the page of GIMP on FlatHub:
https://www.flathub.org/apps/details/org.gimp.GIMP
Here, within this page, plug-ins for GIMP should appear ... There should be a list for them (& beside the name of each plug-in should appear it's size). The name of plug-ins within this suggested list should be click-able, so that click any of them will redirect user to the page of that plug-in where user can read it's description like any other application .... 

If you apply what I suggested, then user indeed have no any need to use a very buggy frontend like GNOME software / Plasma Discover.

**Comment by TingPing** [comment] 2020-06-25 06:06
Duplicate of #47

**Closed by TingPing** 2020-06-25 06:06 UTC
