### ISSUE TITLE
Screenshots appear in the wrong order

### ISSUE THREAD

**Issue by mjog** [flathub/linux-store-frontend#170] opened 2019-03-17 15:42 UTC
The order in which screenshots show up on the Flathub web site is the reverse of the order they appear in both the appdata file and in GNOME Software.

It's kinda sucky having your hero shot show up last, you know? :)

See Geary for example, these are reversed, the complete main window screenshot should be first: https://flathub.org/apps/details/org.gnome.Geary

**Comment by jgarciao** [comment] 2019-03-18 09:21
This is a duplicate of 
https://github.com/flathub/linux-store-frontend/issues/80

**Closed by jgarciao** 2019-03-18 09:21 UTC
