### ISSUE TITLE
Extensions could be shown as optional installs in the pages of the apps they extend

### ISSUE THREAD

**Issue by somas95** [flathub/linux-store-frontend#114] opened 2018-05-23 23:44 UTC
As GNOME software does, extensions could be shown in the app's pages that they extend, or at least be listed along the other apps on the flathub store (maybe on their own category, as they are not apps), as currently is impossible to install any extension from flathub itself

**Comment by TingPing** [comment] 2018-05-24 10:31
Duplicate of #47

**Closed by TingPing** 2018-05-24 10:31 UTC
