### ISSUE TITLE
Add shadows to application icons

### ISSUE THREAD

**Issue by felipeborges** [flathub/linux-store-frontend#169] opened 2019-03-12 12:23 UTC
In GNOME 3.32 there are new icons that require some shadow when placed on top of a light background. See https://gitlab.gnome.org/GNOME/Initiatives/issues/2

![Screenshot from 2019-03-12 13-15-57](https://user-images.githubusercontent.com/365434/54199411-23b9b880-44c9-11e9-9edf-6208508d1505.png)

![Screenshot from 2019-03-12 13-16-46](https://user-images.githubusercontent.com/365434/54199416-26b4a900-44c9-11e9-87e0-86a34080789a.png)

Gtk has a css class for that that could be reused in linux-store-frontend as well. The definition of the "icon-dropshadow" style class in Adwaita is:

```
.icon-dropshadow {
    -gtk-icon-shadow: 0 2px 12px rgba(0, 0, 0, 0.2), 0 1px 2px rgba(0, 0, 0, 0.7);
}
```
* obviously gtk-icon-shadow is gtk specific, but I'm sure you can find some CSS counterpart.

**Comment by jgarciao** [comment] 2019-03-19 09:04
I could add the shadow but that could affect all the apps, unless there is a hint in the appdata

Do you have an image showing the expected result? Gnome Software 3.30 doesn't seem to add this shadow (I don't know about 3.32) and Gnome Boxes [website](https://wiki.gnome.org/Apps/Boxes) still has the old icon

**Comment by felipeborges** [comment] 2019-03-19 09:10
https://gitlab.gnome.org/GNOME/gnome-software/merge_requests/189

I will update the Boxes website.

**Comment by jgarciao** [comment] 2019-03-19 09:15
Thanks. I understand for your patch to Gnome Software that all apps have the shadow now. I will try it in flathub to see how it looks

**Comment by felipeborges** [comment] 2019-03-19 09:33
You can get inspiration from http://jimmac.musichall.cz/stuff/icon-revolution/

What @jimmac seem to be doing there for the dropshadow in CSS is

```
.icon.blurred img {
   -webkit-filter: drop-shadow(0 1px 1px rgba(0,0,0,0.4)) drop-shadow(0 1px 10px rgba(0,0,0,0.1));
          filter: drop-shadow(0 1px 1px rgba(0,0,0,0.4)) drop-shadow(0 1px 10px rgba(0,0,0,0.1));
}
```

Thanks a lot, @jgarciao!

**Comment by jgarciao** [comment] 2019-04-26 05:33
I just tried to add the dropshadow with your example css and gnome boxes looks as you wanted

The problem is that the shadow is affecting all icons. For some of them it doesn't matter much, but I'm afraid some app publishers might not be happy having their icon changed. 

@jimmac @allanday What do you think?


Look at this examples:

- Slack (original and with shadow):
![slack-original](https://user-images.githubusercontent.com/66894/56785318-eef18e80-67f4-11e9-8fa1-c3fcb3c0fdc1.png)
![slack-dropshadow](https://user-images.githubusercontent.com/66894/56785321-f1ec7f00-67f4-11e9-9116-30d52a0070b2.png)

- Kdenlive (original and with shadow):

![kdenlive-original](https://user-images.githubusercontent.com/66894/56785326-fca71400-67f4-11e9-9e1d-59c3288db63a.png)
![kdenlive-dropshadow](https://user-images.githubusercontent.com/66894/56785331-ff096e00-67f4-11e9-94f2-bec978b72ab2.png)

**Comment by jgarciao** [comment] 2019-04-26 07:37
The[ Slack Branding Guidelines](https://a.slack-edge.com/3f2ae/marketing/img/media-kit/Slack-Brand-Guidelines.pdf) explicitly say _Do not use drop shadows or any other effects_  (page 13)

**Comment by jgarciao** [comment] 2019-07-04 14:40
@jimmac @allanday, do you have any comments or suggestions about this issue?

**Comment by jimmac** [comment] 2019-07-04 15:01
That's what we do on the desktop.

**Comment by felipeborges** [comment] 2019-07-08 08:05
We could just provide an SVG already containing the drop shadow.

**Comment by jgarciao** [comment] 2019-07-08 08:54
Or a hint in the appdata file (shadow = true or something similar) in the icon tag

**Comment by felipeborges** [comment] 2019-09-13 12:03
I guess the appstream solution is more reasonable.

Would you be fine if we standardize the custom tag bellow?

```XML
<custom>
  <value key="flathub::use-dropshadow">1</value>
</custom>
```

See the very bottom of the appstream metadata documentation, for the <custom> tag https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#spec-component-filespec

If we decide to go with this approach, it would be nice to communicate this somehow for application developers to know.

**Comment by ferdnyc** [comment] 2019-11-27 15:58
> The[ Slack Branding Guidelines](https://a.slack-edge.com/3f2ae/marketing/img/media-kit/Slack-Brand-Guidelines.pdf) explicitly say _Do not use drop shadows or any other effects_ (page 13)

@jgarciao Devil's advocate: Page 14 also says, "You may not... Distribute or otherwise make available our logos, marks, or assets". Not 100% clear the application icon is (or could possibly be) covered under their branding guidelines, given that. **#JustSayin**

**Comment by ferdnyc** [comment] 2019-11-27 16:03
(@felipeborges My personal, unsolicited 2¢ — not that I'm a GNOME designer or anything — is that, while adding a shadow tag to the AppData might be a useful enhancement, it probably makes sense to update the Boxes logo design in general so that it can be used unmodified against a white background. This hardly seems like the only context where that could happen.)

**Comment by felipeborges** [comment] 2019-11-27 16:07
I guess @jimmac could chime in, please. :)

**Comment by jimmac** [comment] 2019-11-27 17:06
Non systemic approach of providing a baked in shadow for Boxes for Flathub is fine with me if you're fine maintaining that exception.

**Comment by felipeborges** [comment] 2019-11-28 10:00
Works for me.

**Comment by jimmac** [comment] 2019-11-28 10:36
http://jimmac.musichall.cz/stuff/org.gnome.Boxes.Flathub.png
http://jimmac.musichall.cz/stuff/org.gnome.Boxes.Flathub.svg

**Comment by bilelmoussaoui** [comment] 2020-05-11 11:00
This is now fixed

**Closed by bilelmoussaoui** 2020-05-11 11:00 UTC
